import { useEffect, useState } from 'react';
import { CTA, SectionTitle } from './components';
import { mediaUrl, churchApi } from '../services/churchApi';
import './event-gallery.css';

const labels={upcoming:'À VENIR',ongoing:'EN COURS',past:'ACTION RÉALISÉE'};
const formatDate=value=>value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'';
const asset=value=>value&&value.startsWith('/uploads/')?mediaUrl(value):value;
function EventBlock({event}){return <article className="event-gallery-block">{event.image&&<div className="event-cover" style={{backgroundImage:`url(${asset(event.image)})`}} aria-hidden="true"/>}<div className="event-gallery-copy"><span className="gold-label">{labels[event.event_state]||'ACTION DE TERRAIN'}</span><h2>{event.title}</h2><p>{event.description}</p><div className="event-meta">{event.location&&<span>{event.location}</span>}<span>{formatDate(event.start_at)}</span>{event.end_at&&event.event_state==='ongoing'&&<span>Jusqu’au {formatDate(event.end_at)}</span>}</div></div>{event.photos?.length>0&&<div className="event-gallery-scroll" aria-label={`Photos de ${event.title}`}>{event.photos.map(photo=><figure className="event-gallery-photo" key={`${event.id}-${photo.id}`}><div className="event-gallery-photo-image" role="img" aria-label={photo.caption||''} style={{backgroundImage:`url(${asset(photo.image)})`,backgroundPosition:photo.position||'center'}}/><figcaption>{photo.caption}</figcaption></figure>)}</div>}</article>}
export default function EventsPage(){const[events,setEvents]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;churchApi.events().then(p=>{const d=Array.isArray(p)?p:p?.data;if(active&&Array.isArray(d))setEvents(d)}).catch(()=>{}).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);const upcoming=events.filter(e=>e.event_state==='upcoming'),ongoing=events.filter(e=>e.event_state==='ongoing'),past=events.filter(e=>e.event_state==='past');return <><section className="section page-title-simple"><div className="container"><SectionTitle eyebrow="GOSPEL BREAK CHAIN MINISTRY" title="ÉVÉNEMENTS & ACTIONS DE TERRAIN" text="Découvrez les prochains rendez-vous, les actions actuellement menées et les témoignages en images des missions déjà réalisées."/></div></section><section className="section"><div className="container events-gallery-list">{loading&&<p className="event-empty">Chargement des événements...</p>}{!loading&&upcoming.length>0&&<section className="event-group"><SectionTitle eyebrow="PROCHAINEMENT" title="Événements à venir" text="Les prochains rendez-vous du ministère."/>{upcoming.map(e=><EventBlock event={e} key={e.id}/>)}</section>}{!loading&&ongoing.length>0&&<section className="event-group"><SectionTitle eyebrow="EN CE MOMENT" title="Événement en cours" text="Les actions actuellement sur le terrain."/>{ongoing.map(e=><EventBlock event={e} key={e.id}/>)}</section>}{!loading&&past.length>0&&<section className="event-group"><SectionTitle eyebrow="HISTORIQUE" title="Actions réalisées" text="Retrouvez les actions passées et leurs photos."/>{past.map(e=><EventBlock event={e} key={e.id}/>)}</section>}{!loading&&!events.length&&<p className="event-empty">Aucun événement publié pour le moment.</p>}<div className="event-gallery-cta"><h2>Une action à soutenir</h2><p>La mission continue. Vous pouvez porter ces actions dans la prière ou contribuer à leur réalisation.</p><div><CTA to="/prayer">Prier pour la mission</CTA><CTA dark to="/donate">Soutenir la mission</CTA></div></div></div></section></>}
