import React,{useEffect,useState} from 'react';
import {churchApi,mediaUrl} from '../services/churchApi';
import './admin-events.css';

const empty={title:'',description:'',location:'',start_at:'',end_at:'',image:'',status:'published',is_featured:false,display_order:0};
const stateLabel={upcoming:'À venir',ongoing:'En cours',past:'Terminé',archived:'Archivé'};
const inputDate=v=>v?String(v).replace(' ','T').slice(0,16):'';
const asset=v=>v&&v.startsWith('/uploads/')?mediaUrl(v):v;

export default function AdminEventsPage(){
 const[events,setEvents]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[cover,setCover]=useState(null),[gallery,setGallery]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const r=await churchApi.admin.list('events');setEvents(r.data||[])}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const reset=()=>{setEditing(null);setForm(empty);setCover(null);setGallery([]);setSelected(null)};const change=(n,v)=>setForm(x=>({...x,[n]:v}));
 const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{let id=editing,result;if(id){await churchApi.admin.update('events',id,form)}else{result=await churchApi.admin.create('events',form);id=result.id;await churchApi.admin.update('events',id,form)}const slug=(result?.slug||form.title||'event').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`event-${id}`;const year=new Date(form.start_at).getFullYear()||new Date().getFullYear();if(cover){const r=await churchApi.admin.upload(cover,`events/${year}/${slug}`);await churchApi.admin.update('events',id,{image:r.data.path})}for(let i=0;i<gallery.length;i++){const r=await churchApi.admin.upload(gallery[i],`events/${year}/${slug}`);await churchApi.admin.addPhoto(id,{image:r.data.path,sort_order:i})}reset();await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const edit=e=>{setEditing(e.id);setForm({title:e.title||'',description:e.description||'',location:e.location||'',start_at:inputDate(e.start_at||e.event_date),end_at:inputDate(e.end_at||e.event_date),image:e.image||'',status:e.status||'published',is_featured:Boolean(e.is_featured),display_order:e.display_order||0});setCover(null);setGallery([]);setSelected(null);window.scrollTo({top:0,behavior:'smooth'})};
 const archive=async id=>{if(!window.confirm('Archiver cet événement ?'))return;try{await churchApi.admin.remove('events',id);await load()}catch(e){setError(e.message)}};
 const openGallery=async e=>{try{const r=await churchApi.admin.get('events',e.id);setSelected(r.data)}catch(e){setError(e.message)}};
 const deletePhoto=async id=>{if(!window.confirm('Supprimer cette photo ?'))return;try{await churchApi.admin.remove('event-photos',id);if(selected)await openGallery(selected)}catch(e){setError(e.message)}};
 return <div className="admin-events-page">{error&&<div className="form-error dashboard-error">{error}</div>}
 <section className="admin-panel admin-event-form"><div className="event-form-head"><div><span className="dashboard-label">GESTION DU CONTENU</span><h2>{editing?'Modifier l’événement':'Créer un événement'}</h2><p className="admin-muted">Les dates déterminent automatiquement l’état public.</p></div>{editing&&<button type="button" className="btn outline" onClick={reset}>Nouvel événement</button>}</div>
 <form className="event-form-grid" onSubmit={submit}><label>Titre<input value={form.title} onChange={e=>change('title',e.target.value)} required/></label><label>Lieu<input value={form.location} onChange={e=>change('location',e.target.value)}/></label><label>Début<input type="datetime-local" value={form.start_at} onChange={e=>change('start_at',e.target.value)} required/></label><label>Fin<input type="datetime-local" value={form.end_at} onChange={e=>change('end_at',e.target.value)} required/></label><label className="wide">Description<textarea rows="5" value={form.description} onChange={e=>change('description',e.target.value)}/></label><label>Publication<select value={form.status} onChange={e=>change('status',e.target.value)}><option value="published">Publié</option><option value="draft">Brouillon</option></select></label><label>Ordre d’affichage<input type="number" min="0" value={form.display_order} onChange={e=>change('display_order',e.target.value)}/></label><label className="check-field"><input type="checkbox" checked={form.is_featured} onChange={e=>change('is_featured',e.target.checked)}/> Mettre en avant</label><label className="wide">Image de couverture<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setCover(e.target.files?.[0]||null)}/><small>Optimisée automatiquement si GD/WebP est disponible.</small></label><label className="wide">Galerie photos<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setGallery(Array.from(e.target.files||[]))}/><small>{gallery.length} nouvelle(s) photo(s).</small></label><div className="form-actions wide"><button className="btn" disabled={saving}>{saving?'Enregistrement...':editing?'Enregistrer les modifications':'Créer l’événement'}</button></div></form></section>
 <section className="admin-panel"><div className="admin-list-head"><div><h2>Événements</h2><p className="admin-muted">À venir, en cours, terminés et archivés.</p></div><span>{events.length}</span></div>{loading?<p className="admin-muted">Chargement...</p>:events.length===0?<p className="admin-muted">Aucun événement.</p>:<div className="event-admin-list">{events.map(e=><article key={e.id} className={e.archived_at?'is-archived':''}>{e.image?<img src={asset(e.image)} alt=""/>:<div className="event-admin-placeholder">EVENT</div>}<div className="event-admin-main"><div className="event-admin-title"><strong>{e.title}</strong><span className={`event-state ${e.event_state}`}>{stateLabel[e.event_state]||e.status}</span></div><p>{e.location||'Lieu non renseigné'} · {new Date(e.start_at||e.event_date).toLocaleString('fr-FR')}</p><small>{e.photo_count||0} photo(s) · {e.is_featured?'Mis en avant':'Standard'}</small></div><div className="row-actions"><button onClick={()=>edit(e)}>Modifier</button><button onClick={()=>openGallery(e)}>Photos</button>{!e.archived_at&&<button onClick={()=>archive(e.id)}>Archiver</button>}</div></article>)}</div>}</section>
 {selected&&<section className="admin-panel event-gallery-admin"><div className="panel-head"><div><span className="dashboard-label">GALERIE</span><h2>{selected.title}</h2></div><button className="btn outline" onClick={()=>setSelected(null)}>Fermer</button></div><div className="admin-photo-grid">{(selected.photos||[]).map(p=><figure key={p.id}><img src={asset(p.image)} alt={p.caption||''}/><figcaption><span>{p.caption||'Sans légende'}</span><button onClick={()=>deletePhoto(p.id)}>Supprimer</button></figcaption></figure>)}</div>{!selected.photos?.length&&<p className="admin-muted">Aucune photo.</p>}</section>}
 </div>;
}
