// Bible verse collection used by the public hero and administration sidebar.
// Translation: Louis Segond 1910 (public domain).
// Keep one consistent shape so every view can consume the same source.

export const bibleVerses = [
  // Amour de Dieu pour l'homme
  { id: 1, reference: 'Jean 3:16', text: 'Car Dieu a tant aimé le monde qu’il a donné son Fils unique, afin que quiconque croit en lui ne périsse point, mais qu’il ait la vie éternelle.', theme: 'love' },
  { id: 2, reference: 'Jean 3:17', text: 'Dieu, en effet, n’a pas envoyé son Fils dans le monde pour qu’il juge le monde, mais pour que le monde soit sauvé par lui.', theme: 'love' },
  { id: 3, reference: 'Romains 5:8', text: 'Mais Dieu prouve son amour envers nous, en ce que, lorsque nous étions encore des pécheurs, Christ est mort pour nous.', theme: 'love' },
  { id: 4, reference: '1 Jean 4:9', text: 'L’amour de Dieu a été manifesté envers nous en ce que Dieu a envoyé son Fils unique dans le monde, afin que nous vivions par lui.', theme: 'love' },
  { id: 5, reference: '1 Jean 4:10', text: 'Cet amour consiste, non point en ce que nous avons aimé Dieu, mais en ce qu’il nous a aimés et a envoyé son Fils.', theme: 'love' },
  { id: 6, reference: '1 Jean 4:16', text: 'Dieu est amour; et celui qui demeure dans l’amour demeure en Dieu, et Dieu demeure en lui.', theme: 'love' },
  { id: 7, reference: '1 Jean 4:19', text: 'Pour nous, nous l’aimons, parce qu’il nous a aimés le premier.', theme: 'love' },
  { id: 8, reference: 'Éphésiens 2:4', text: 'Mais Dieu, qui est riche en miséricorde, à cause du grand amour dont il nous a aimés.', theme: 'love' },
  { id: 9, reference: 'Éphésiens 2:5', text: 'Il nous a rendus à la vie avec Christ; c’est par grâce que vous êtes sauvés.', theme: 'love' },
  { id: 10, reference: 'Éphésiens 2:7', text: 'Afin de montrer dans les siècles à venir l’infinie richesse de sa grâce par sa bonté envers nous en Jésus-Christ.', theme: 'love' },
  { id: 11, reference: 'Éphésiens 3:17', text: 'En sorte que Christ habite dans vos cœurs par la foi; afin qu’étant enracinés et fondés dans l’amour.', theme: 'love' },
  { id: 12, reference: 'Éphésiens 3:18', text: 'Vous puissiez comprendre avec tous les saints quelle est la largeur, la longueur, la profondeur et la hauteur.', theme: 'love' },
  { id: 13, reference: 'Éphésiens 3:19', text: 'Et connaître l’amour de Christ, qui surpasse toute connaissance, en sorte que vous soyez remplis jusqu’à toute la plénitude de Dieu.', theme: 'love' },
  { id: 14, reference: 'Romains 8:35', text: 'Qui nous séparera de l’amour de Christ? Sera-ce la tribulation, ou l’angoisse, ou la persécution?', theme: 'love' },
  { id: 15, reference: 'Romains 8:37', text: 'Mais dans toutes ces choses nous sommes plus que vainqueurs par celui qui nous a aimés.', theme: 'love' },
  { id: 16, reference: 'Romains 8:38-39', text: 'Rien ne pourra nous séparer de l’amour de Dieu manifesté en Jésus-Christ notre Seigneur.', theme: 'love' },
  { id: 17, reference: 'Jérémie 31:3', text: 'Je t’aime d’un amour éternel; c’est pourquoi je te conserve ma bonté.', theme: 'love' },
  { id: 18, reference: 'Ésaïe 43:4', text: 'Parce que tu as du prix à mes yeux, parce que tu es honoré et que je t’aime.', theme: 'love' },
  { id: 19, reference: 'Ésaïe 49:15', text: 'Une femme oublie-t-elle l’enfant qu’elle allaite? Même si elle l’oubliait, moi je ne t’oublierai point.', theme: 'love' },
  { id: 20, reference: 'Ésaïe 54:10', text: 'Quand les montagnes s’éloigneraient et que les collines chancelleraient, mon amour ne s’éloignera point de toi.', theme: 'love' },
  { id: 21, reference: 'Lamentations 3:22', text: 'Les bontés de l’Éternel ne sont pas épuisées, ses compassions ne sont pas à leur terme.', theme: 'love' },
  { id: 22, reference: 'Lamentations 3:23', text: 'Elles se renouvellent chaque matin. Oh! que ta fidélité est grande!', theme: 'love' },
  { id: 23, reference: 'Psaume 103:8', text: 'L’Éternel est miséricordieux et compatissant, lent à la colère et riche en bonté.', theme: 'love' },
  { id: 24, reference: 'Psaume 103:11', text: 'Mais autant les cieux sont élevés au-dessus de la terre, autant sa bonté est grande pour ceux qui le craignent.', theme: 'love' },
  { id: 25, reference: 'Psaume 103:13', text: 'Comme un père a compassion de ses enfants, l’Éternel a compassion de ceux qui le craignent.', theme: 'love' },
  { id: 26, reference: 'Psaume 107:1', text: 'Louez l’Éternel, car il est bon, car sa miséricorde dure à toujours!', theme: 'love' },
  { id: 27, reference: 'Psaume 136:1', text: 'Louez l’Éternel, car il est bon, car sa miséricorde dure à toujours!', theme: 'love' },
  { id: 28, reference: 'Psaume 145:8', text: 'L’Éternel est miséricordieux et compatissant, lent à la colère et plein de bonté.', theme: 'love' },
  { id: 29, reference: 'Psaume 145:9', text: 'L’Éternel est bon envers tous, et ses compassions s’étendent sur toutes ses œuvres.', theme: 'love' },
  { id: 30, reference: 'Psaume 86:5', text: 'Car tu es bon, Seigneur, tu pardonnes, tu es plein d’amour pour tous ceux qui t’invoquent.', theme: 'love' },
  { id: 31, reference: 'Psaume 34:9', text: 'Sentez et voyez combien l’Éternel est bon! Heureux l’homme qui cherche en lui son refuge!', theme: 'love' },
  { id: 32, reference: 'Psaume 23:6', text: 'Oui, le bonheur et la grâce m’accompagneront tous les jours de ma vie.', theme: 'love' },
  { id: 33, reference: 'Psaume 36:8', text: 'Combien est précieuse ta bonté, ô Dieu! À l’ombre de tes ailes les fils de l’homme cherchent un refuge.', theme: 'love' },
  { id: 34, reference: 'Psaume 63:4', text: 'Car ta bonté vaut mieux que la vie: mes lèvres célèbrent tes louanges.', theme: 'love' },
  { id: 35, reference: 'Psaume 117:2', text: 'Car sa bonté pour nous est grande, et sa fidélité dure à toujours.', theme: 'love' },
  { id: 36, reference: 'Psaume 118:1', text: 'Louez l’Éternel, car il est bon, car sa miséricorde dure à toujours!', theme: 'love' },
  { id: 37, reference: 'Psaume 119:64', text: 'La terre, ô Éternel! est pleine de ta bonté.', theme: 'love' },
  { id: 38, reference: 'Psaume 130:7', text: 'Car la miséricorde est auprès de l’Éternel, et la rédemption est auprès de lui en abondance.', theme: 'love' },
  { id: 39, reference: 'Psaume 147:3', text: 'Il guérit ceux qui ont le cœur brisé, et il panse leurs blessures.', theme: 'love' },
  { id: 40, reference: 'Nahum 1:7', text: 'L’Éternel est bon, il est un refuge au jour de la détresse; il connaît ceux qui se confient en lui.', theme: 'love' },
  { id: 41, reference: 'Michée 7:18', text: 'Quel Dieu est semblable à toi, qui pardonnes l’iniquité et qui oublies les péchés?', theme: 'love' },
  { id: 42, reference: 'Michée 7:19', text: 'Tu jetteras au fond de la mer tous leurs péchés.', theme: 'love' },
  { id: 43, reference: 'Sophonie 3:17', text: 'L’Éternel, ton Dieu, est au milieu de toi, comme un héros qui sauve; il fera de toi sa plus grande joie.', theme: 'love' },
  { id: 44, reference: 'Deutéronome 7:9', text: 'Sache donc que l’Éternel, ton Dieu, est Dieu. Ce Dieu fidèle garde son alliance et sa bonté.', theme: 'love' },
  { id: 45, reference: 'Deutéronome 10:18', text: 'Il fait droit à l’orphelin et à la veuve, il aime l’étranger et lui donne de la nourriture et des vêtements.', theme: 'love' },
  { id: 46, reference: 'Deutéronome 30:9', text: 'L’Éternel prendra de nouveau plaisir à ton bonheur, comme il prenait plaisir à celui de tes pères.', theme: 'love' },
  { id: 47, reference: 'Josué 1:9', text: 'Fortifie-toi et prends courage! Ne t’effraie point et ne t’épouvante point, car l’Éternel, ton Dieu, est avec toi.', theme: 'love' },
  { id: 48, reference: '1 Samuel 2:30', text: 'J’honorerai celui qui m’honore.', theme: 'love' },
  { id: 49, reference: '2 Chroniques 16:9', text: 'Car l’Éternel étend ses regards sur toute la terre, pour soutenir ceux dont le cœur est tout entier à lui.', theme: 'love' },
  { id: 50, reference: 'Néhémie 9:17', text: 'Mais toi, tu es un Dieu prêt à pardonner, compatissant et miséricordieux, lent à la colère et riche en bonté.', theme: 'love' },
  { id: 51, reference: 'Proverbes 3:3', text: 'Que la bonté et la fidélité ne t’abandonnent pas; lie-les à ton cou.', theme: 'love' },
  { id: 52, reference: 'Proverbes 3:11-12', text: 'Car l’Éternel châtie celui qu’il aime, comme un père l’enfant qu’il chérit.', theme: 'love' },
  { id: 53, reference: 'Proverbes 8:17', text: 'J’aime ceux qui m’aiment, et ceux qui me cherchent me trouvent.', theme: 'love' },
  { id: 54, reference: 'Ésaïe 41:10', text: 'Ne crains rien, car je suis avec toi; ne promène pas des regards inquiets, car je suis ton Dieu.', theme: 'love' },
  { id: 55, reference: 'Ésaïe 41:13', text: 'Car je suis l’Éternel, ton Dieu, qui fortifie ta droite, qui te dis: Ne crains rien, je viens à ton secours.', theme: 'love' },
  { id: 56, reference: 'Ésaïe 46:4', text: 'Jusqu’à votre vieillesse je serai le même, jusqu’à vos cheveux blancs je vous soutiendrai.', theme: 'love' },
  { id: 57, reference: 'Ésaïe 55:7', text: 'Que le méchant abandonne sa voie, et l’homme d’iniquité ses pensées; qu’il retourne à l’Éternel, qui aura pitié de lui.', theme: 'love' },
  { id: 58, reference: 'Ézéchiel 18:23', text: 'Ce que je désire, est-ce que le méchant meure? N’est-ce pas qu’il change de conduite et qu’il vive?', theme: 'love' },
  { id: 59, reference: 'Osée 11:4', text: 'Je les tirai avec des liens d’humanité, avec des cordages d’amour.', theme: 'love' },
  { id: 60, reference: 'Joël 2:13', text: 'Revenez à l’Éternel, votre Dieu; car il est compatissant et miséricordieux, lent à la colère et riche en bonté.', theme: 'love' },
  { id: 61, reference: 'Zacharie 1:3', text: 'Revenez à moi, dit l’Éternel des armées, et je reviendrai à vous.', theme: 'love' },
  { id: 62, reference: 'Matthieu 11:28', text: 'Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.', theme: 'love' },
  { id: 63, reference: 'Matthieu 11:29', text: 'Prenez mon joug sur vous et recevez mes instructions, car je suis doux et humble de cœur.', theme: 'love' },
  { id: 64, reference: 'Matthieu 18:14', text: 'Ce n’est pas la volonté de votre Père qui est dans les cieux qu’il se perde un seul de ces petits.', theme: 'love' },
  { id: 65, reference: 'Luc 15:20', text: 'Comme il était encore loin, son père le vit et fut ému de compassion, il courut se jeter à son cou et le baisa.', theme: 'love' },
  { id: 66, reference: 'Luc 19:10', text: 'Car le Fils de l’homme est venu chercher et sauver ce qui était perdu.', theme: 'love' },
  { id: 67, reference: 'Jean 10:10', text: 'Moi, je suis venu afin que les brebis aient la vie, et qu’elles soient dans l’abondance.', theme: 'love' },
  { id: 68, reference: 'Jean 10:11', text: 'Je suis le bon berger. Le bon berger donne sa vie pour ses brebis.', theme: 'love' },
  { id: 69, reference: 'Jean 14:18', text: 'Je ne vous laisserai pas orphelins, je viendrai à vous.', theme: 'love' },
  { id: 70, reference: 'Jean 15:9', text: 'Comme le Père m’a aimé, je vous ai aussi aimés. Demeurez dans mon amour.', theme: 'love' },
  { id: 71, reference: 'Jean 15:13', text: 'Il n’y a pas de plus grand amour que de donner sa vie pour ses amis.', theme: 'love' },
  { id: 72, reference: 'Romains 5:5', text: 'L’amour de Dieu est répandu dans nos cœurs par le Saint-Esprit qui nous a été donné.', theme: 'love' },
  { id: 73, reference: 'Romains 8:32', text: 'Lui, qui n’a point épargné son propre Fils, mais qui l’a livré pour nous tous, comment ne nous donnera-t-il pas aussi toutes choses avec lui?', theme: 'love' },
  { id: 74, reference: '2 Corinthiens 5:19', text: 'Dieu était en Christ, réconciliant le monde avec lui-même, en n’imputant point aux hommes leurs offenses.', theme: 'love' },
  { id: 75, reference: 'Tite 3:4-5', text: 'La bonté de Dieu notre Sauveur et son amour pour les hommes ont été manifestés.', theme: 'love' },

  // Évangélisation, salut et mission
  { id: 76, reference: 'Matthieu 28:19', text: 'Allez, faites de toutes les nations des disciples, les baptisant au nom du Père, du Fils et du Saint-Esprit.', theme: 'evangelism' },
  { id: 77, reference: 'Matthieu 28:20', text: 'Et voici, je suis avec vous tous les jours, jusqu’à la fin du monde.', theme: 'evangelism' },
  { id: 78, reference: 'Marc 16:15', text: 'Allez par tout le monde, et prêchez la bonne nouvelle à toute la création.', theme: 'evangelism' },
  { id: 79, reference: 'Marc 16:16', text: 'Celui qui croira et qui sera baptisé sera sauvé, mais celui qui ne croira pas sera condamné.', theme: 'evangelism' },
  { id: 80, reference: 'Actes 1:8', text: 'Vous recevrez une puissance, le Saint-Esprit survenant sur vous, et vous serez mes témoins.', theme: 'evangelism' },
  { id: 81, reference: 'Actes 4:12', text: 'Il n’y a de salut en aucun autre; car il n’y a sous le ciel aucun autre nom qui ait été donné parmi les hommes, par lequel nous devions être sauvés.', theme: 'evangelism' },
  { id: 82, reference: 'Actes 8:4', text: 'Ceux qui avaient été dispersés allaient de lieu en lieu, annonçant la bonne nouvelle de la parole.', theme: 'evangelism' },
  { id: 83, reference: 'Actes 8:35', text: 'Alors Philippe, ouvrant la bouche et commençant par ce passage, lui annonça la bonne nouvelle de Jésus.', theme: 'evangelism' },
  { id: 84, reference: 'Actes 10:42', text: 'Et Jésus nous a ordonné de prêcher au peuple et d’attester qu’il est celui qui a été établi par Dieu juge des vivants et des morts.', theme: 'evangelism' },
  { id: 85, reference: 'Actes 13:47', text: 'Je t’ai établi pour être la lumière des nations, pour que tu portes le salut jusqu’aux extrémités de la terre.', theme: 'evangelism' },
  { id: 86, reference: 'Actes 20:24', text: 'Je ne fais pour moi-même aucun cas de ma vie, comme si elle m’était précieuse, pourvu que j’accomplisse ma course et le ministère que j’ai reçu.', theme: 'evangelism' },
  { id: 87, reference: 'Romains 1:16', text: 'Je n’ai point honte de l’Évangile: c’est une puissance de Dieu pour le salut de quiconque croit.', theme: 'evangelism' },
  { id: 88, reference: 'Romains 10:9', text: 'Si tu confesses de ta bouche le Seigneur Jésus, et si tu crois dans ton cœur que Dieu l’a ressuscité des morts, tu seras sauvé.', theme: 'evangelism' },
  { id: 89, reference: 'Romains 10:10', text: 'Car c’est en croyant du cœur qu’on parvient à la justice, et c’est en confessant de la bouche qu’on parvient au salut.', theme: 'evangelism' },
  { id: 90, reference: 'Romains 10:13', text: 'Quiconque invoquera le nom du Seigneur sera sauvé.', theme: 'evangelism' },
  { id: 91, reference: 'Romains 10:14', text: 'Comment l’invoqueront-ils en qui ils n’ont pas cru? Et comment croiront-ils en celui dont ils n’ont pas entendu parler?', theme: 'evangelism' },
  { id: 92, reference: 'Romains 10:15', text: 'Qu’ils sont beaux les pieds de ceux qui annoncent la paix, de ceux qui annoncent de bonnes nouvelles!', theme: 'evangelism' },
  { id: 93, reference: '1 Corinthiens 1:18', text: 'La prédication de la croix est une folie pour ceux qui périssent; mais pour nous qui sommes sauvés, elle est une puissance de Dieu.', theme: 'evangelism' },
  { id: 94, reference: '1 Corinthiens 9:22', text: 'Je me suis fait tout à tous, afin d’en sauver de toute manière quelques-uns.', theme: 'evangelism' },
  { id: 95, reference: '1 Corinthiens 9:23', text: 'Je fais tout à cause de l’Évangile, afin d’y avoir part.', theme: 'evangelism' },
  { id: 96, reference: '1 Corinthiens 15:3', text: 'Je vous ai enseigné avant tout, comme je l’avais aussi reçu, que Christ est mort pour nos péchés, selon les Écritures.', theme: 'evangelism' },
  { id: 97, reference: '1 Corinthiens 15:4', text: 'Il a été enseveli, et il est ressuscité le troisième jour, selon les Écritures.', theme: 'evangelism' },
  { id: 98, reference: '2 Corinthiens 5:20', text: 'Nous faisons donc les fonctions d’ambassadeurs pour Christ, comme si Dieu exhortait par nous.', theme: 'evangelism' },
  { id: 99, reference: '2 Corinthiens 5:21', text: 'Celui qui n’a point connu le péché, il l’a fait devenir péché pour nous, afin que nous devenions en lui justice de Dieu.', theme: 'evangelism' },
  { id: 100, reference: 'Galates 2:20', text: 'J’ai été crucifié avec Christ; et si je vis, ce n’est plus moi qui vis, c’est Christ qui vit en moi.', theme: 'evangelism' },
  { id: 101, reference: 'Galates 6:9', text: 'Ne nous lassons pas de faire le bien; car nous moissonnerons au temps convenable, si nous ne nous relâchons pas.', theme: 'evangelism' },
  { id: 102, reference: 'Éphésiens 5:8', text: 'Autrefois vous étiez ténèbres, et maintenant vous êtes lumière dans le Seigneur. Marchez comme des enfants de lumière!', theme: 'evangelism' },
  { id: 103, reference: 'Philippiens 2:15', text: 'Afin que vous soyez irréprochables et purs, des enfants de Dieu irrépréhensibles au milieu d’une génération perverse et corrompue, parmi laquelle vous brillez comme des flambeaux.', theme: 'evangelism' },
  { id: 104, reference: 'Colossiens 4:5', text: 'Conduisez-vous avec sagesse envers ceux du dehors, et rachetez le temps.', theme: 'evangelism' },
  { id: 105, reference: 'Colossiens 4:6', text: 'Que votre parole soit toujours accompagnée de grâce, assaisonnée de sel, afin que vous sachiez comment il faut répondre à chacun.', theme: 'evangelism' },
  { id: 106, reference: '1 Thessaloniciens 1:8', text: 'La parole du Seigneur a retenti de chez vous dans la Macédoine et dans l’Achaïe; votre foi en Dieu s’est fait connaître en tout lieu.', theme: 'evangelism' },
  { id: 107, reference: '2 Timothée 1:8', text: 'N’aie donc point honte du témoignage à rendre à notre Seigneur, ni de moi son prisonnier; mais souffre avec moi pour l’Évangile.', theme: 'evangelism' },
  { id: 108, reference: '2 Timothée 4:2', text: 'Prêche la parole, insiste en toute occasion, favorable ou non, reprends, censure, exhorte, avec toute douceur et en instruisant.', theme: 'evangelism' },
  { id: 109, reference: 'Tite 2:11', text: 'Car la grâce de Dieu, source de salut pour tous les hommes, a été manifestée.', theme: 'evangelism' },
  { id: 110, reference: 'Tite 3:5', text: 'Il nous a sauvés, non à cause des œuvres de justice que nous aurions faites, mais selon sa miséricorde.', theme: 'evangelism' },
  { id: 111, reference: 'Hébreux 12:2', text: 'Ayant les regards sur Jésus, qui suscite la foi et la mène à la perfection.', theme: 'evangelism' },
  { id: 112, reference: 'Jacques 5:20', text: 'Celui qui ramènera un pécheur de la voie où il s’était égaré sauvera une âme de la mort et couvrira une multitude de péchés.', theme: 'evangelism' },
  { id: 113, reference: '1 Pierre 2:9', text: 'Vous êtes une race élue, un sacerdoce royal, une nation sainte, un peuple acquis, afin que vous annonciez les vertus de celui qui vous a appelés des ténèbres à son admirable lumière.', theme: 'evangelism' },
  { id: 114, reference: '1 Pierre 3:15', text: 'Soyez toujours prêts à vous défendre, avec douceur et respect, devant quiconque vous demande raison de l’espérance qui est en vous.', theme: 'evangelism' },
  { id: 115, reference: '2 Pierre 3:9', text: 'Le Seigneur ne tarde pas dans l’accomplissement de la promesse, mais il use de patience envers vous, ne voulant pas qu’aucun périsse.', theme: 'evangelism' },
  { id: 116, reference: '1 Jean 5:11', text: 'Et voici ce témoignage, c’est que Dieu nous a donné la vie éternelle, et que cette vie est dans son Fils.', theme: 'evangelism' },
  { id: 117, reference: '1 Jean 5:12', text: 'Celui qui a le Fils a la vie; celui qui n’a pas le Fils de Dieu n’a pas la vie.', theme: 'evangelism' },
  { id: 118, reference: 'Apocalypse 3:20', text: 'Voici, je me tiens à la porte, et je frappe. Si quelqu’un entend ma voix et ouvre la porte, j’entrerai chez lui.', theme: 'evangelism' },
  { id: 119, reference: 'Apocalypse 22:17', text: 'Que celui qui a soif vienne; que celui qui veut prenne de l’eau de la vie, gratuitement.', theme: 'evangelism' },
  { id: 120, reference: 'Ésaïe 6:8', text: 'Me voici, envoie-moi.', theme: 'evangelism' },
  { id: 121, reference: 'Ésaïe 52:7', text: 'Qu’ils sont beaux sur les montagnes, les pieds de celui qui apporte de bonnes nouvelles, qui publie la paix!', theme: 'evangelism' },
  { id: 122, reference: 'Ésaïe 55:11', text: 'Ainsi en est-il de ma parole, qui sort de ma bouche: elle ne retourne point à moi sans effet.', theme: 'evangelism' },
  { id: 123, reference: 'Psaume 96:2', text: 'Chantez à l’Éternel, bénissez son nom, annoncez de jour en jour son salut!', theme: 'evangelism' },
  { id: 124, reference: 'Psaume 96:3', text: 'Racontez parmi les nations sa gloire, parmi tous les peuples ses merveilles!', theme: 'evangelism' },
  { id: 125, reference: 'Psaume 105:1', text: 'Louez l’Éternel, invoquez son nom! Faites connaître parmi les peuples ses hauts faits!', theme: 'evangelism' },
  { id: 126, reference: 'Psaume 107:2', text: 'Qu’ainsi disent les rachetés de l’Éternel, ceux qu’il a délivrés de la puissance de l’ennemi.', theme: 'evangelism' },
  { id: 127, reference: 'Psaume 126:5', text: 'Ceux qui sèment avec larmes moissonneront avec chants d’allégresse.', theme: 'evangelism' },
  { id: 128, reference: 'Psaume 126:6', text: 'Celui qui marche en pleurant, quand il porte la semence, revient avec allégresse quand il porte ses gerbes.', theme: 'evangelism' },
  { id: 129, reference: 'Daniel 12:3', text: 'Ceux qui auront été sages brilleront comme la splendeur du ciel, et ceux qui auront enseigné la justice à la multitude brilleront comme les étoiles.', theme: 'evangelism' },
  { id: 130, reference: 'Jonas 3:10', text: 'Dieu vit qu’ils agissaient ainsi et qu’ils revenaient de leur mauvaise voie. Alors Dieu se repentit du mal qu’il avait résolu de leur faire.', theme: 'evangelism' },
  { id: 131, reference: 'Matthieu 5:14', text: 'Vous êtes la lumière du monde. Une ville située sur une montagne ne peut être cachée.', theme: 'evangelism' },
  { id: 132, reference: 'Matthieu 5:16', text: 'Que votre lumière luise ainsi devant les hommes, afin qu’ils voient vos bonnes œuvres et glorifient votre Père.', theme: 'evangelism' },
  { id: 133, reference: 'Matthieu 9:37', text: 'La moisson est grande, mais il y a peu d’ouvriers.', theme: 'evangelism' },
  { id: 134, reference: 'Matthieu 9:38', text: 'Priez donc le maître de la moisson d’envoyer des ouvriers dans sa moisson.', theme: 'evangelism' },
  { id: 135, reference: 'Matthieu 24:14', text: 'Cette bonne nouvelle du royaume sera prêchée dans le monde entier, pour servir de témoignage à toutes les nations.', theme: 'evangelism' },
  { id: 136, reference: 'Marc 1:15', text: 'Le temps est accompli, et le royaume de Dieu est proche. Repentez-vous, et croyez à la bonne nouvelle.', theme: 'evangelism' },
  { id: 137, reference: 'Luc 4:18', text: 'Il m’a envoyé pour guérir ceux qui ont le cœur brisé, pour proclamer aux captifs la délivrance.', theme: 'evangelism' },
  { id: 138, reference: 'Luc 4:19', text: 'Pour publier une année de grâce du Seigneur.', theme: 'evangelism' },
  { id: 139, reference: 'Luc 9:2', text: 'Il les envoya prêcher le royaume de Dieu, et guérir les malades.', theme: 'evangelism' },
  { id: 140, reference: 'Luc 10:2', text: 'La moisson est grande, mais il y a peu d’ouvriers. Priez donc le maître de la moisson d’envoyer des ouvriers.', theme: 'evangelism' },
  { id: 141, reference: 'Luc 24:47', text: 'La repentance et le pardon des péchés seraient prêchés en son nom à toutes les nations.', theme: 'evangelism' },
  { id: 142, reference: 'Jean 1:29', text: 'Voici l’Agneau de Dieu, qui ôte le péché du monde.', theme: 'evangelism' },
  { id: 143, reference: 'Jean 1:12', text: 'Mais à tous ceux qui l’ont reçue, à ceux qui croient en son nom, elle a donné le pouvoir de devenir enfants de Dieu.', theme: 'evangelism' },
  { id: 144, reference: 'Jean 3:36', text: 'Celui qui croit au Fils a la vie éternelle; celui qui ne croit pas au Fils ne verra point la vie.', theme: 'evangelism' },
  { id: 145, reference: 'Jean 4:35', text: 'Levez les yeux, et regardez les champs qui déjà blanchissent pour la moisson.', theme: 'evangelism' },
  { id: 146, reference: 'Jean 20:21', text: 'Comme le Père m’a envoyé, moi aussi je vous envoie.', theme: 'evangelism' },
  { id: 147, reference: 'Actes 2:21', text: 'Alors quiconque invoquera le nom du Seigneur sera sauvé.', theme: 'evangelism' },
  { id: 148, reference: 'Actes 16:31', text: 'Crois au Seigneur Jésus, et tu seras sauvé, toi et ta famille.', theme: 'evangelism' },
  { id: 149, reference: '2 Corinthiens 5:17', text: 'Si quelqu’un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées.', theme: 'evangelism' },
  { id: 150, reference: '1 Timothée 2:4', text: 'Dieu veut que tous les hommes soient sauvés et parviennent à la connaissance de la vérité.', theme: 'evangelism' },
];
